FROM apache/superset:latest

USER root
WORKDIR /app

COPY pyproject.toml setup.py MANIFEST.in README.md ./
COPY superset ./superset
COPY superset-core ./superset-core

RUN uv pip install --python /app/.venv/bin/python --no-cache -e /app \
    && uv pip install --python /app/.venv/bin/python --no-cache psycopg2-binary

USER superset

