server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/ {
        proxy_pass http://super-app-backend:8090/;
    }

    location /superset-mfe/ {
        proxy_pass http://super-app-superset-ui:5174/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /superset/public/ {
        proxy_pass http://super-app-backend:8090/superset/public/;
    }

    location /superset/operation/ {
        proxy_pass http://super-app-backend:8090/superset/operation/;
    }

    location / {
        proxy_pass http://super-app-ui:5173/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
